# Generated by Django 5.2.16 on 2026-08-09 02:40

import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-2', '0 to 2 years (Toddlers)'), ('3-5', '3 to 5 years (Early Readers)'), ('6-8', '6 to 8 years (Early Chapter Books)'), ('9-12', '9 to 12 years (Middle Grade)'), ('13+', '13+ years (Young Adult)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri (Meitei)'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Odia', 'Odia'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santali', 'Santali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='theme',
            field=models.CharField(blank=True, choices=[('life_skills', 'Life Skills'), ('mental_health', 'Mental Health'), ('adventure', 'Adventure & Fantasy'), ('stem', 'STEM & Science'), ('friendship', 'Friendship & Family'), ('values', 'Moral Values & Ethics')], max_length=50),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=store.models.book_cover_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as main cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in gallery')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.book')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
