# Generated by Django 5.2.16 on 2026-09-10 17:50

import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0005_remove_book_cover_image_alter_book_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('book', 'toy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Item Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('material', models.CharField(blank=True, choices=[('wooden', 'Wooden'), ('plastic', 'Plastic'), ('fabric', 'Fabric / Plush'), ('silicone', 'Silicone'), ('paper_cardboard', 'Paper / Cardboard'), ('metal', 'Metal')], max_length=30)),
                ('age_group', models.CharField(blank=True, choices=[('0-2', '0 to 2 years (Toddlers)'), ('3-5', '3 to 5 years (Early Readers)'), ('6-8', '6 to 8 years (Early Chapter Books)'), ('9-12', '9 to 12 years (Middle Grade)'), ('13+', '13+ years (Young Adult)')], max_length=20)),
                ('theme', models.CharField(blank=True, choices=[('life_skills', 'Life Skills'), ('mental_health', 'Mental Health'), ('adventure', 'Adventure & Fantasy'), ('stem', 'STEM & Science'), ('friendship', 'Friendship & Family'), ('values', 'Moral Values & Ethics')], max_length=50)),
                ('summary', models.TextField(blank=True, verbose_name='Product Summary')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toys', to='store.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='toys', to='store.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=store.models.toy_cover_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as main cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in gallery')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.toy')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
