# Generated by Django 5.2.16 on 2026-09-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_orderitem_book_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('TOY', 'Toy')], default='BOOK', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_type')},
        ),
    ]
